### PR TITLE
Feature/get all time entries

### PR DESCRIPTION
**Pull request by conorliv**
@kylesuss Thanks for making this API wrapper. I started using it in my project and needed a new feature, so I implemented it. Please review my PR when you have a moment. Thanks! :smile:

### CODE REVIEW

**Comment by kylesuss** [comment]
Hey @conorliv , glad you made use of the wrapper. Unfortunately, I don't have access to this github org anymore, so you'll have to wait for approval from someone else at TackMobile.

**Comment by conorliv** [comment]
@kylesuss  Thanks for your response. Who from TackMobile would be the best person to ping about a PR on this repo?

**Comment by kylesuss** [comment]
Probably @thillerson

**Comment by thillerson** [comment]
I heard my name. @kylesuss Is this PR good? I'm not familiar with what's going on enough to tell...

**Comment by kylesuss** [comment]
@conorliv I haven't looked at the 10k API in a while so I wanted to double check that the endpoint you created exists. All the time entry endpoints I can find are namespaced by [user](https://www.10000ft.com/reference/api-documentation/time-entries#top) or [project](https://www.10000ft.com/reference/api-documentation/time-entries-project#top). Do you have a link to the docs so I can verify?

**Comment by conorliv** [comment]
@kylesuss You're right - the endpoint that I added doesn't exist in 10kft's documentation, but it exists in reality. I contacted their support about a faster way to get all of my company's employee's time entries than making a separate request to get each employee's time entries and they told me to use this endpoint. This endpoint provides a way to get all time entries for all employees in a single API request.

**Comment by kylesuss** [comment]
Sure, thanks for the info @conorliv . @thillerson the actual codes looks good to me, though I don't have the credentials to test this anymore.

**Comment by thillerson** [comment]
Ok. Cool, thanks for looking at it, Kyle, and thanks for the code, Conor!

**Pull request merged**
